version: '3.3'
services:

  Notary:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10002:10002"
      - "10006:10006"
      - "10004:10004"
      - "10009:10009"
    image: corda/node:3.3
    container_name: notary
    volumes:
      - ./nodes/notary/corda-notary.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/notary/certificates/:/opt/corda/certificates/
      - ./nodes/notary/network-parameters:/opt/corda/network-parameters

  CordaNetworkMap:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10012:10002"
      - "10016:10006"
      - "10014:10004"
      - "10019:10009"
    image: corda/networkmap:3.3
    container_name: networkmap
    volumes:
      - ./nodes/networkmap/corda-networkmap.conf:/opt/corda/node.conf

  CordaNodeA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10022:10002"
      - "10026:10006"
      - "10024:10004"
      - "10029:10009"
    image: corda/node:3.3
    container_name: banka
    volumes:
      - ./nodes/banka/corda-banka.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/banka/certificates/:/opt/corda/certificates/
      - ./nodes/banka/network-parameters:/opt/corda/network-parameters
    depends_on:
      - CordaNetworkMap

  CordaNodeB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10032:10002"
      - "10036:10006"
      - "10034:10004"
      - "10039:10009"
    image: corda/node:3.3
    container_name: bankb
    volumes:
      - ./nodes/bankb/corda-bankb.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/bankb/certificates/:/opt/corda/certificates/
      - ./nodes/bankb/network-parameters:/opt/corda/network-parameters
    depends_on:
      - CordaNetworkMap

  CordaNodeC:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 3.3
    env_file:
      - ./corda_docker.env
    ports:
      - "10042:10002"
      - "10046:10006"
      - "10044:10004"
      - "10049:10009"
    image: corda/node:3.3
    container_name: bankc
    volumes:
      - ./nodes/bankc/corda-bankc.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/bankc/certificates/:/opt/corda/certificates/
      - ./nodes/bankc/network-parameters:/opt/corda/network-parameters
    depends_on:
      - CordaNetworkMap

networks:
  corda:
